# -*- coding: utf-8 -*-
"""HGBrasilFinace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wQRs62xzx5jVFgoZ6lp5d4z8n5AySvKg
"""

#Feito por Danielzaõ
import requests

url = 'https://api.hgbrasil.com/finance'
valor = requests.get(url)

valor_compra = float(valor.json()['results']['currencies']['USD']['buy'])

valor_venda = float(valor.json()['results']['currencies']['USD']['sell'])

name = str(valor.json()['results']['currencies']['USD']['name'])

variation = float(valor.json()['results']['currencies']['USD']['variation'])


valor_compraeur = float(valor.json()['results']['currencies']['EUR']['buy'])

valor_vendaeur = float(valor.json()['results']['currencies']['EUR']['sell'])

nameeur = str(valor.json()['results']['currencies']['EUR']['name'])

variationeur = float(valor.json()['results']['currencies']['EUR']['variation'])


print('Nome da moeda ',name)
print('o valor de compra é ',valor_compra)
print('o valor de venda ',valor_venda)
print('o valor da variação na ultima hora é ',variation ,'\n')

print('Nome da moeda ',nameeur)
print('o valor de compra é ',valor_compraeur)
print('o valor de venda ',valor_vendaeur)
print('o valor da variação na ultima hora é ',variationeur ,'\n')